<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
           http://maven.apache.org/POM/4.0.0
           http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>org.cyclops.packs</groupId>
  <artifactId>cyclops-id-neoforge</artifactId>
  <version>26.2</version>
  <packaging>pom</packaging>

  <dependencies>
    <dependency>
      <groupId>org.cyclops.cyclopscore</groupId>
      <artifactId>cyclopscore-26.2-neoforge</artifactId>
      <version>1.30.0-1066</version>
    </dependency>

    <dependency>
      <groupId>org.cyclops.commoncapabilities</groupId>
      <artifactId>commoncapabilities-26.2-neoforge</artifactId>
      <version>2.11.8-365</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integrateddynamics</groupId>
      <artifactId>integrateddynamics-26.2-neoforge</artifactId>
      <version>1.33.4-1925</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedtunnels</groupId>
      <artifactId>integratedtunnels-26.2-neoforge</artifactId>
      <version>1.9.6-654</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedcrafting</groupId>
      <artifactId>integratedcrafting-26.2-neoforge</artifactId>
      <version>1.4.7-614</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedterminals</groupId>
      <artifactId>integratedterminals-26.2-neoforge</artifactId>
      <version>1.7.0-803</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedscripting</groupId>
      <artifactId>integratedscripting-26.2-neoforge</artifactId>
      <version>1.0.22-444</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedrest</groupId>
      <artifactId>integratedrest-26.2-neoforge</artifactId>
      <version>1.1.15-207</version>
    </dependency>

    <dependency>
      <groupId>org.cyclops.integratednbt</groupId>
      <artifactId>integratednbt-26.2-neoforge</artifactId>
      <version>1.6.1-63</version>
    </dependency>

    <!--><dependency>
      <groupId>org.cyclops.integratedmekanism</groupId>
      <artifactId>integratedmekanism-26.2-neoforge</artifactId>
      <version>1.0.3-89</version>
    </dependency>
    
    <dependency>
      <groupId>mekanism</groupId>
      <artifactId>Mekanism</artifactId>
      <version>1.21.1-10.7.17.83</version>
      <classifier>all</classifier>
    </dependency>-->

    <!--<dependency>
      <groupId>com.refinedmods.refinedstorage</groupId>
      <artifactId>refinedstorage-neoforge</artifactId>
      <version>3.2.0</version>
    </dependency>-->
  </dependencies>
</project>
