<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
           http://maven.apache.org/POM/4.0.0
           http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>org.cyclops.packs</groupId>
  <artifactId>cyclops-all-deps-neoforge</artifactId>
  <version>26.2</version>
  <packaging>pom</packaging>

  <dependencies>
    <dependency>
      <groupId>org.cyclops.cyclopscore</groupId>
      <artifactId>cyclopscore-26.2-neoforge</artifactId>
      <version>1.30.0-1066</version>
    </dependency>

    <dependency>
      <groupId>org.cyclops.flopper</groupId>
      <artifactId>flopper-26.2-neoforge</artifactId>
      <version>1.1.9-238</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.structuredcrafting</groupId>
      <artifactId>structuredcrafting-26.2-neoforge</artifactId>
      <version>0.2.14-217</version>
    </dependency>

    <dependency>
      <groupId>org.cyclops.commoncapabilities</groupId>
      <artifactId>commoncapabilities-26.2-neoforge</artifactId>
      <version>2.11.8-365</version>
    </dependency>
  
    <dependency>
      <groupId>org.cyclops.capabilityproxy</groupId>
      <artifactId>capabilityproxy-26.2-neoforge</artifactId>
      <version>2.2.3-219</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.everlastingabilities</groupId>
      <artifactId>everlastingabilities-26.2-neoforge</artifactId>
      <version>2.5.10-392</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.energeticsheep</groupId>
      <artifactId>energeticsheep-26.2-neoforge</artifactId>
      <version>1.2.0-256</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.colossalchests</groupId>
      <artifactId>colossalchests-26.2-neoforge</artifactId>
      <version>1.8.16-268</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.iconexporter</groupId>
      <artifactId>iconexporter-26.2-neoforge</artifactId>
      <version>1.4.2-212</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integrateddynamics</groupId>
      <artifactId>integrateddynamics-26.2-neoforge</artifactId>
      <version>1.33.4-1914</version>
    </dependency>
    
    <!-- Integrated Dynamics deps: start -->
    
    <dependency>
      <groupId>mezz.jei</groupId>
      <artifactId>jei-26.2-neoforge</artifactId>
      <version>30.15.0.110</version>
    </dependency>
    
    <!--><dependency>
      <groupId>mcjty.theoneprobe</groupId>
      <artifactId>theoneprobe</artifactId>
      <version>1.21_neo-12.0.8-7</version>
    </dependency>-->
    
    <dependency>
      <groupId>com.github.glitchfiend</groupId>
      <artifactId>TerraBlender-neoforge</artifactId>
      <version>26.2-26.2.0.0.2</version>
    </dependency>

    <!--<dependency> While we have support, the gametest "evilcraft:gametestsbloodinfuser_testbloodinfuseremptyfluidcontainercreativeblooddrop" fails for some reason when architectury is present. They are probably breaking things...
      <groupId>me.shedaniel</groupId>
      <artifactId>RoughlyEnoughItems-neoforge</artifactId>
      <version>26.2.820</version>
      <exclusions>
          <exclusion>
              <groupId>*</groupId>
              <artifactId>*</artifactId>
          </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>me.shedaniel.cloth</groupId>
      <artifactId>cloth-config-neoforge</artifactId>
      <version>26.2.155</version>
    </dependency>

    <dependency>
      <groupId>dev.architectury</groupId>
      <artifactId>architectury-neoforge</artifactId>
      <version>21.0.6</version>
    </dependency>-->

    <!--><dependency>
      <groupId>com.almostreliable.mods</groupId>
      <artifactId>almostunified-neoforge</artifactId>
      <version>1.21.1-1.4.1</version>
    </dependency>-->

    <dependency>
      <groupId>curse.maven</groupId>
      <artifactId>jade-324717</artifactId>
      <version>8281956</version>
    </dependency>

    <!--><dependency>
      <groupId>com.refinedmods.refinedstorage</groupId>
      <artifactId>refinedstorage-neoforge</artifactId>
      <version>3.2.0</version>
    </dependency>-->
    
    <!-- Integrated Dynamics deps: end -->
    
    <dependency>
      <groupId>org.cyclops.integratedtunnels</groupId>
      <artifactId>integratedtunnels-26.2-neoforge</artifactId>
      <version>1.9.6-654</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedcrafting</groupId>
      <artifactId>integratedcrafting-26.2-neoforge</artifactId>
      <version>1.4.7-607</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedterminals</groupId>
      <artifactId>integratedterminals-26.2-neoforge</artifactId>
      <version>1.7.0-803</version>
    </dependency>
    
    <!-- Integrated Terminals deps: start -->
    
    <dependency>
      <groupId>top.theillusivec4.curios</groupId>
      <artifactId>curios-neoforge</artifactId>
      <version>16.0.0+26.2</version>
    </dependency>

    <!--><dependency>
      <groupId>dev.emi</groupId>
      <artifactId>emi-neoforge</artifactId>
      <version>1.1.22+1.21.1</version>
    </dependency>-->

    <!-- Integrated Terminals deps: end -->
    
    <dependency>
      <groupId>org.cyclops.integratedscripting</groupId>
      <artifactId>integratedscripting-26.2-neoforge</artifactId>
      <version>1.0.22-422</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedrest</groupId>
      <artifactId>integratedrest-26.2-neoforge</artifactId>
      <version>1.1.15-207</version>
    </dependency>

    <dependency>
      <groupId>org.cyclops.integratednbt</groupId>
      <artifactId>integratednbt-26.2-neoforge</artifactId>
      <version>1.6.1-63</version>
    </dependency>
    
    <!--><dependency>
      <groupId>org.cyclops.integratedmekanism</groupId>
      <artifactId>integratedmekanism-26.2-neoforge</artifactId>
      <version>1.0.4-102</version>
    </dependency>
    
    <dependency>
      <groupId>mekanism</groupId>
      <artifactId>Mekanism</artifactId>
      <version>1.21.1-10.7.19.85</version>
      <classifier>all</classifier>
    </dependency>-->
    
    <!-- Integrated Mekanism deps: end -->
    
    <dependency>
      <groupId>org.cyclops.evilcraft</groupId>
      <artifactId>evilcraft-26.2-neoforge</artifactId>
      <version>1.2.98-1004</version>
    </dependency>
    
    <!-- Evilcraft deps: start -->
    <!-- They overlap with deps of the mods above, so no need to re-list them. -->
    <!-- Evilcraft deps: end -->
  
  </dependencies>
</project>
