<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
           http://maven.apache.org/POM/4.0.0
           http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>org.cyclops.packs</groupId>
  <artifactId>cyclops-all-neoforge</artifactId>
  <version>1.21.1</version>
  <packaging>pom</packaging>

  <dependencies>
    <dependency>
      <groupId>org.cyclops.cyclopscore</groupId>
      <artifactId>cyclopscore-1.21.1-neoforge</artifactId>
      <version>1.29.2-1063</version>
    </dependency>

    <dependency>
      <groupId>org.cyclops.flopper</groupId>
      <artifactId>flopper-1.21.1-neoforge</artifactId>
      <version>1.1.8-236</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.structuredcrafting</groupId>
      <artifactId>structuredcrafting-1.21.1-neoforge</artifactId>
      <version>0.2.13-218</version>
    </dependency>

    <dependency>
      <groupId>org.cyclops.commoncapabilities</groupId>
      <artifactId>commoncapabilities-1.21.1-neoforge</artifactId>
      <version>2.11.5-363</version>
    </dependency>
  
    <dependency>
      <groupId>org.cyclops.capabilityproxy</groupId>
      <artifactId>capabilityproxy-1.21.1-neoforge</artifactId>
      <version>2.2.1-222</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.everlastingabilities</groupId>
      <artifactId>everlastingabilities-1.21.1-neoforge</artifactId>
      <version>2.5.6-390</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.energeticsheep</groupId>
      <artifactId>energeticsheep-1.21.1-neoforge</artifactId>
      <version>1.1.18-253</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.colossalchests</groupId>
      <artifactId>colossalchests-1.21.1-neoforge</artifactId>
      <version>1.8.14-266</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.iconexporter</groupId>
      <artifactId>iconexporter-1.21.1-neoforge</artifactId>
      <version>1.4.1-210</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integrateddynamics</groupId>
      <artifactId>integrateddynamics-1.21.1-neoforge</artifactId>
      <version>1.34.1-1928</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedtunnels</groupId>
      <artifactId>integratedtunnels-1.21.1-neoforge</artifactId>
      <version>1.9.4-671</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedcrafting</groupId>
      <artifactId>integratedcrafting-1.21.1-neoforge</artifactId>
      <version>1.4.7-620</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedterminals</groupId>
      <artifactId>integratedterminals-1.21.1-neoforge</artifactId>
      <version>1.7.0-800</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedscripting</groupId>
      <artifactId>integratedscripting-1.21.1-neoforge</artifactId>
      <version>1.0.26-448</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedrest</groupId>
      <artifactId>integratedrest-1.21.1-neoforge</artifactId>
      <version>1.1.15-205</version>
    </dependency>

    <dependency>
      <groupId>org.cyclops.integratednbt</groupId>
      <artifactId>integratednbt-1.21.1-neoforge</artifactId>
      <version>1.6.2-54</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedmekanism</groupId>
      <artifactId>integratedmekanism-1.21.1-neoforge</artifactId>
      <version>1.0.4-110</version>
    </dependency>
    
    <dependency>
      <groupId>mekanism</groupId>
      <artifactId>Mekanism</artifactId>
      <version>1.21.1-10.7.19.85</version>
      <classifier>all</classifier>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.evilcraft</groupId>
      <artifactId>evilcraft-1.21.1-neoforge</artifactId>
      <version>1.2.93-1021</version>
    </dependency>

    <dependency>
      <groupId>com.refinedmods.refinedstorage</groupId>
      <artifactId>refinedstorage-neoforge</artifactId>
      <version>2.0.9</version>
    </dependency>
  
  </dependencies>
</project>