<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
           http://maven.apache.org/POM/4.0.0
           http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>org.cyclops.packs</groupId>
  <artifactId>cyclops-all-neoforge</artifactId>
  <version>1.21.1</version>
  <packaging>pom</packaging>

  <dependencies>
    <dependency>
      <groupId>org.cyclops.cyclopscore</groupId>
      <artifactId>cyclopscore-1.21.1-neoforge</artifactId>
      <version>1.29.0-944</version>
    </dependency>

    <dependency>
      <groupId>org.cyclops.flopper</groupId>
      <artifactId>flopper-1.21.1-neoforge</artifactId>
      <version>1.1.8-211</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.structuredcrafting</groupId>
      <artifactId>structuredcrafting-1.21.1-neoforge</artifactId>
      <version>0.2.13-189</version>
    </dependency>

    <dependency>
      <groupId>org.cyclops.commoncapabilities</groupId>
      <artifactId>commoncapabilities-1.21.1-neoforge</artifactId>
      <version>2.11.3-322</version>
    </dependency>
  
    <dependency>
      <groupId>org.cyclops.capabilityproxy</groupId>
      <artifactId>capabilityproxy-1.21.1-neoforge</artifactId>
      <version>2.2.1-187</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.everlastingabilities</groupId>
      <artifactId>everlastingabilities-1.21.1-neoforge</artifactId>
      <version>2.5.5-319</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.energeticsheep</groupId>
      <artifactId>energeticsheep-1.21.1-neoforge</artifactId>
      <version>1.1.18-189</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.colossalchests</groupId>
      <artifactId>colossalchests-1.21.1-neoforge</artifactId>
      <version>1.8.14-222</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.iconexporter</groupId>
      <artifactId>iconexporter-1.21.1-neoforge</artifactId>
      <version>1.4.0-174</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integrateddynamics</groupId>
      <artifactId>integrateddynamics-1.21.1-neoforge</artifactId>
      <version>1.32.0-1647</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedtunnels</groupId>
      <artifactId>integratedtunnels-1.21.1-neoforge</artifactId>
      <version>1.9.3-600</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedcrafting</groupId>
      <artifactId>integratedcrafting-1.21.1-neoforge</artifactId>
      <version>1.4.4-526</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedterminals</groupId>
      <artifactId>integratedterminals-1.21.1-neoforge</artifactId>
      <version>1.6.25-716</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedscripting</groupId>
      <artifactId>integratedscripting-1.21.1-neoforge</artifactId>
      <version>1.0.21-335</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedrest</groupId>
      <artifactId>integratedrest-1.21.1-neoforge</artifactId>
      <version>1.1.15-180</version>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.integratedmekanism</groupId>
      <artifactId>integratedmekanism-1.21.1-neoforge</artifactId>
      <version>1.0.3-90</version>
    </dependency>
    
    <dependency>
      <groupId>mekanism</groupId>
      <artifactId>Mekanism</artifactId>
      <version>1.21.1-10.7.18.84</version>
      <classifier>all</classifier>
    </dependency>
    
    <dependency>
      <groupId>org.cyclops.evilcraft</groupId>
      <artifactId>evilcraft-1.21.1-neoforge</artifactId>
      <version>1.2.82-801</version>
    </dependency>
  
  </dependencies>
</project>